const userRoute = require('./user.route');
const userinfoRoute = require('./userinfo.route');
const userjabatanRoute = require('./userjabatan.route');
const userkepangkatanRoute = require('./userkepangkatan.route');
const userpendidikanRoute = require('./userpendidikan.route');
const roleRoute = require('./role.route');
const permissionRoute = require('./permission.route');
const bidangRoute = require('./bidang.route');
const layananRoute = require('./layanan.route');
const layananformRoute = require('./layananform.route');
const layananfileRoute = require('./layananfile.route');
const inputformRoute = require('./inputform.route');
const historyformRoute = require('./historyform.route');
const layanansuratRoute = require('./layanansurat.route');
const kecamatanRoute = require('./kecamatan.route');
const desaRoute = require('./desa.route');
const termconditionRoute = require('./termcondition.route');
const pengaduanRoute = require('./pengaduan.route');
const galeriRoute = require('./galeri.route');
const faqRoute = require('./faq.route');
const surveyformRoute = require('./surveyform.route');
const bannerRoute = require('./banner.route');
const bkdprofileRoute = require('./bkdprofile.route');


module.exports = function (app, urlApi) {
    app.use(urlApi, userRoute);
    app.use(urlApi, userinfoRoute);
    app.use(urlApi, userjabatanRoute);
    app.use(urlApi, userkepangkatanRoute);
    app.use(urlApi, userpendidikanRoute);
    app.use(urlApi, roleRoute);
    app.use(urlApi, permissionRoute);
    app.use(urlApi, bidangRoute);
    app.use(urlApi, layananRoute);
    app.use(urlApi, layananformRoute);
    app.use(urlApi, layananfileRoute);
    app.use(urlApi, inputformRoute);
    app.use(urlApi, historyformRoute);
    app.use(urlApi, layanansuratRoute);
    app.use(urlApi, kecamatanRoute);
    app.use(urlApi, desaRoute);
    app.use(urlApi, termconditionRoute);
    app.use(urlApi, pengaduanRoute);
    app.use(urlApi, galeriRoute);
    app.use(urlApi, faqRoute);
    app.use(urlApi, surveyformRoute);
    app.use(urlApi, bannerRoute);
    app.use(urlApi, bkdprofileRoute);
}