const userRoute = require("./user.route");
const userinfoRoute = require("./userinfo.route");
const userjabatanRoute = require("./userjabatan.route");
const userkepangkatanRoute = require("./userkepangkatan.route");
const userpendidikanRoute = require("./userpendidikan.route");
const userkgbRoute = require("./userkgb.route");
const userpenghargaanRoute = require("./userpenghargaan.route");
const userpelatihanRoute = require("./userpelatihan.route");
const userspouseRoute = require("./userspouse.route");
const userdescendantRoute = require("./userdescendant.route");
const userdokumenRoute = require("./userdokumen.route");
const userfeedbackRoute = require("./userfeedback.route");
const permissionRoute = require("./permissions.route");
const bidangRoute = require("./bidang.route");
const layananRoute = require("./layanan.route");
const layananformRoute = require("./layananform.route");
const layananfileRoute = require("./layananfile.route");
const inputformRoute = require("./inputform.route");
const historyformRoute = require("./historyform.route");
const kecamatanRoute = require("./kecamatan.route");
const desaRoute = require("./desa.route");
const pangkatRoute = require("./pangkat.route");
const termconditionRoute = require("./termcondition.route");
const pengaduanRoute = require("./pengaduan.route");
const galeriRoute = require("./galeri.route");
const faqRoute = require("./faq.route");
const bannerRoute = require("./banner.route");
const bkdprofileRoute = require("./bkdprofile.route");
const bkdstrukturRoute = require("./bkdstruktur.route");
const selectedstrukturRoute = require("./selectedstruktur.route");
const beritaRoute = require("./berita.route");
const manualbookRoute = require("./manualbook.route");
const regulasiRoute = require("./regulasi.route");
const dashboardRoute = require("./dashboard.route");
const suratRoute = require("./surat.route");
const roleRoute = require("./role.route");
const documentRoute = require("./documentprint.route");
const strukturRoute = require("./struktur.route");

module.exports = function (app, urlApi) {
  app.use(urlApi, userRoute);
  app.use(urlApi, userinfoRoute);
  app.use(urlApi, userjabatanRoute);
  app.use(urlApi, userkepangkatanRoute);
  app.use(urlApi, userpendidikanRoute);
  app.use(urlApi, userkgbRoute);
  app.use(urlApi, userpenghargaanRoute);
  app.use(urlApi, userpelatihanRoute);
  app.use(urlApi, userspouseRoute);
  app.use(urlApi, userdescendantRoute);
  app.use(urlApi, userdokumenRoute);
  app.use(urlApi, userfeedbackRoute);
  app.use(urlApi, permissionRoute);
  app.use(urlApi, bidangRoute);
  app.use(urlApi, layananRoute);
  app.use(urlApi, layananformRoute);
  app.use(urlApi, layananfileRoute);
  app.use(urlApi, inputformRoute);
  app.use(urlApi, historyformRoute);
  app.use(urlApi, kecamatanRoute);
  app.use(urlApi, desaRoute);
  app.use(urlApi, pangkatRoute);
  app.use(urlApi, termconditionRoute);
  app.use(urlApi, pengaduanRoute);
  app.use(urlApi, galeriRoute);
  app.use(urlApi, faqRoute);
  app.use(urlApi, bannerRoute);
  app.use(urlApi, bkdprofileRoute);
  app.use(urlApi, bkdstrukturRoute);
  app.use(urlApi, selectedstrukturRoute);
  app.use(urlApi, beritaRoute);
  app.use(urlApi, manualbookRoute);
  app.use(urlApi, regulasiRoute);
  app.use(urlApi, dashboardRoute);
  app.use(urlApi, suratRoute);
  app.use(urlApi, roleRoute);
  app.use(urlApi, documentRoute);
  app.use(urlApi, strukturRoute);
};
